### ISSUE TITLE
question about BERT_{E}+CRF

### ISSUE THREAD

**Issue by wjczf123** [NUSTM/GCDDA#3]
Hi, junjie.

I have a question about BERT_{E}+CRF.
1. Compared with BERT_{B}+CRF, does BERT_{E}+CRF use extra combined data of E-commerce reviews from the Amazon Electronics dataset and the Yelp Challenge? 
2. If so, does your method use this combined data?

**Comment by LemonDrinkTea** [comment]
Thank you for your attention to our paper. We didn't directly use extra data to train the downstream tasks. We only use extra combined data to train the BERT_{B} by MLM , and finally get the BERT_{E}.

**Comment by wjczf123** [comment]
Thanks for your reply.

**Comment by wjczf123** [comment]
Can you tell me the instructions to reproduce the results of baseline BERT_{E}+CRF?

**Comment by wjczf123** [comment]
Hi, junjie.

1. Can I reproduce BERT_{E}+CRF with the following command?
cd aeoe
cd ae_oe_bert_crf
bash ./run_bert_e_sdl.sh

2. I got outputs of above command.
 联合任务： precision: 0.8478038771817984 recall: 0.688510962732851 f1: 0.7598943251083702. 
 Does the performance of 联合任务 correspond to OP in Table 2?

**Comment by wjczf123** [comment]
I look forward to your reply. Thank you.

**Comment by LemonDrinkTea** [comment]
Yes, 联合任务 means op, we forget to change the name.

**Comment by wjczf123** [comment]
Thanks. 
Another question is ''Can I reproduce BERT_{E}+CRF with the following command?''
cd aeoe
cd ae_oe_bert_crf
bash ./run_bert_e_sdl.sh

**Comment by LemonDrinkTea** [comment]
you can change the train data files to reproduce the no domain adpatation baseline BERT_{E}+CRF.

**Comment by wjczf123** [comment]
Can you be more specific?
I look the code and found that nothing seems to need to be changed.

**Comment by LemonDrinkTea** [comment]
you can change the the code in #254:"eval_examples = processor.get_test_examples_pseudo_label(args.data_dir,args.domain_pair,args.dataset_split, args.task_type)" to "eval_examples = processor.get_test_examples_da_test(args.data_dir,args.domain_pair,args.dataset_split, args.task_type)"

**Comment by wjczf123** [comment]
OK. Thanks for your help. Best regards!
